# 1. Conexión a tu MySQL en la Nube (AWS RDS)
# Hemos sustituido localhost por tu nuevo Endpoint de Amazon
spring.datasource.url=jdbc:mysql://tfg-socialgame.chhamc4j5wyi.us-east-1.rds.amazonaws.com:3306/socialgame
spring.datasource.username=UTFG1347
spring.datasource.password=tfg-master123

# 2. Driver de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Estrategia de creación de tablas
# 'update' hará que Spring cree las tablas automáticamente en AWS al arrancar
spring.jpa.hibernate.ddl-auto=update

# 4. Ver qué está pasando "bajo el capó"
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Añadimos el dialecto específico para MySQL 8 (el que usa AWS)
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# 5. Puerto de la API
server.port=8080

# 6. Configuración adicional para evitar desconexiones en la nube
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5